### ISSUE TITLE
Could not install flatbuffers==20190709135844

### ISSUE THREAD

**Issue by veerendrav** [mklissa/dceo#2]
Hey,

I am using python 3.8 in a conda environment and I got this error while running "pip install -r requirements.txt" for setting up dceo

ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.9,<4.0; 0.1.8 Requires-Python >=3.9; 0.1.81 Requires-Python >=3.9; 0.1.82 Requires-Python >=3.9; 0.1.83 Requires-Python >=3.9; 0.1.84 Requires-Python >=3.9; 0.1.85 Requires-Python >=3.9; 0.1.86 Requires-Python >=3.9; 1.2.0 Requires-Python >=3.9; 1.4.0 Requires-Python >=3.9; 1.4.1 Requires-Python >=3.9; 1.5.0 Requires-Python >=3.9; 1.5.1 Requires-Python >=3.9; 1.5.2 Requires-Python >=3.9; 1.6.0 Requires-Python >=3.10; 1.7.0 Requires-Python >=3.10; 1.8.0 Requires-Python >=3.11
ERROR: Could not find a version that satisfies the requirement flatbuffers==20190709135844 (from versions: 1.9, 1.10, 1.11, 1.12, 2.0, 2.0.7, 22.9.24, 22.10.26, 22.11.23, 22.12.6, 23.1.4, 23.1.20, 23.1.21, 23.3.3, 23.5.8, 23.5.9, 23.5.26, 24.3.6, 24.3.7)
ERROR: No matching distribution found for flatbuffers==20190709135844

Please help

**Comment by mklissa** [comment]
hey @veerendrav, can you try version 2.0? If that doesn't work then try removing this dependency, I am not sure it is necessary.

**Comment by veerendrav** [comment]
Thanks @mklissa. Will try
