### ISSUE TITLE
Question about grid experiments.

### ISSUE THREAD

**Issue by leekwoon** [mklissa/dceo#3]
First of all, thank you for the awesome paper which is an delight to read. 
Is is possible to run grid maze (or nine room) experiments with this code base?

Kind Regards,
LKW

**Comment by mklissa** [comment]
Hello @leekwoon, thank you for your kind message. Unfortunately this code is not for the grid world experiments band cause these were done within DeepMind. I would suggest that a good starting point for experiments on grid would be this repo https://github.com/tarod13/laplacian_dual_dynamics
